### ISSUE TITLE
Generators showing visually as one tier above

### ISSUE THREAD

**Issue by mathiashjelmer** [jbettaque/FancyGens-Bugtracker#8] opened 2022-03-24 01:26 UTC
As shown in the picture:
![image](https://user-images.githubusercontent.com/63245440/159823534-8c1612a1-a058-499b-9cc1-0e89c70b86a5.png)
The copper bar, is spawned from wheat. Circled in red. While the melom spawned from the pumpkin. Both are a drop lower than the intended (based on the visuals)

**Comment by mathiashjelmer** [comment] 2022-03-24 01:26
Should prob have gotten a better picture

**Comment by jbettaque** [comment] 2022-03-24 04:10
this is caused by a bug during upgrading. This bug is fixed in the next update, however currently wrong gens will still show as the wrong gen until broken or upgraded.

**Closed as completed by jbettaque** 2022-03-24 04:10 UTC
Labels: bug
